In [213]:
import pandas as pd
from ydata_profiling import ProfileReport
import csv
import missingno as msno

# solution

In [214]:
a = pd.read_csv('data/darkness-dataset.csv',sep=';', header=None)
a

,0,1,2,3,4
0,"id,name,country_code,position,city,current_com...",NaN,NaN,NaN,NaN
1,"random-id-2468,""Random Name"",""KW"","""",""Kuwait"",...",NaN,NaN,NaN,NaN
2,"random-id-1357,""Random Name"",""IN"",""Random EduT...",NaN,NaN,NaN,NaN
3,"random-id-8642,""Random Name"","""","""","""",""{""""comp...",NaN,NaN,NaN,NaN
4,"random-id-9512,""Random Name"",""UK"",""Design Engi...",NaN,NaN,NaN,NaN
5,"random-id-8642,""Random Name"",""KW"","""",""Kuwait"",...",NaN,NaN,NaN,NaN
6,"random-id-7531,""Random Name"",""KW"","""",""Kuwait"",...",NaN,NaN,NaN,NaN
7,"random-id-7890,""Random Name"",""DZ"",""Logging Ope...",Discuss High Technology Logging Operation PreJ...,Well site Data QC Quality Control.<br>â€¢,Open hole Standard and Advanced Formation Eval...,"Perforation Programs"""","""""""",""""[{""""company"""":""""..."
8,"random-id-4820,""Random Name"",""NG"",""Volkswagen ...",NaN,NaN,NaN,NaN
9,"random-id-9025,""Random Name"",""UK"","""","""",""{""""co...",NaN,NaN,NaN,NaN
10,"random-id-5837,""Random Name"",""EG"",""Food Safety...",NaN,NaN,NaN,NaN
11,"random-id-5847,""Random Name"",""GB"",""Community A...","Commercial projects, all aspects of glass and...","order processing, quality control and ensurin...","Closing Restaurant <!---->"""",""""duration"""":""""M...",NaN
12,"random-id-12286a197,""Random Name"",""EG"",""Senior...",NaN,NaN,NaN,NaN

In [215]:
def lec(row):
    lecteur_csv = csv.reader([row])
    result = []
    
    for i in lecteur_csv:
        result = i 
        
        return result  

    return result

In [216]:
def lecture_par_ligne(row):
    return next(csv.reader([row]))

In [217]:
# dataList = a[0].apply(lecture_par_ligne)

In [218]:
dataList = a[0].apply(lec)
data = pd.DataFrame(dataList.tolist())

In [219]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,id,name,country_code,position,city,current_company,about,posts,experience,url,people_also_viewed,educations_details,education,recommendations_count,avatar,languages,certifications,recommendations,volunteer_experience,courses,followers,connections,current_company_company_id,current_company_name,publications,patents,projects,organizations,input_url,linkedin_id
1,random-id-2468,Random Name,KW,,Kuwait,"{""company_id"":""-seara"",""industry"":""Seara Alime...",Experienced Unit Sales Manager with a demonstr...,"[{""attribution"":""By Random Name"",""created_at"":...",,https://www.linkedin.com/in/random-id-2468,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Alexandria University,,,https://media.licdn.com/dms/image/D4D03AQEK_J4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,-seara,Random Alimentos LTDA,,,,,https://www.linkedin.com/in/random-id-2468,random-id-2468 ``` &#8203;:citation[oaicite:0]...
2,random-id-1357,Random Name,IN,Random EduTech,"Noida, Uttar Pradesh, India","{""company_id"":""byjus"",""industry"":""BYJU'S"",""lin...",,,"[{""company"":""Random EduTech"",""company_id"":""byj...",https://www.linkedin.com/in/random-id-1357,"[{""profile_link"":""https://in.linkedin.com/in/a...",Delhi University,"[{""degree"":""Bachelor's degree"",""description"":n...",,https://media.licdn.com/dms/image/D4D03AQGrszI...,,,,,,,112,byjus,Random EduTech,,,,"[{""end_date"":""Present"",""membership_number"":nul...",https://www.linkedin.com/in/random-id-1357,random-id-1357
3,random-id-8642,Random Name,,,,"{""company_id"":""shepard-exposition-services"",""i...",EXPERIENCED EVENT PLANNER with over three year...,[],[],https://www.linkedin.com/in/random-id-8642?_l=en,[],Guilford Technical Community College,[],,https://media.licdn.com/dms/image/C4E03AQGGXHL...,[],[],[],[],[],190,188,shepard-exposition-services,Random Event Services,[],[],[],,https://www.linkedin.com/in/random-id-8642?_l=en,random-id-8642
4,random-id-9512,Random Name,UK,Design Engineer (System health) at Random Powe...,Galashiels,"{""company_id"":""edf-energy"",""industry"":""EDF (UK...",,[],"[{""description"":""Torness Nuclear Power Station...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5,random-id-8642,Random Name,KW,,Kuwait,"{""company_id"":""global-infinity"",""industry"":""Gl...",Experienced Chief Executive Officer with a dem...,,,https://www.linkedin.com/in/random-id-8642,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Cairo University,,,https://static.licdn.com/aero-v1/sc/h/9c8pery4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,global-infinity,Random Contracting,,,,,https://www.linkedin.com/in/random-id-8642,random-id-8642
6,random-id-7531,Random Name,KW,,Kuwait,"{""company_id"":""global-infinity"",""industry"":""Gl...",Experienced Chief Executive Officer with a dem...,,,https://www.linkedin.com/in/random-id-7531,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Cairo University,,,https://static.licdn.com/aero-v1/sc/h/9c8pery4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,global-infinity,Random Contracting,,,,,https://www.linkedin.com/in/random-id-7531,random-id-7531
7,random-id-7890,Random Name,DZ,Logging Operations & Petrophysical QA/QC super...,"Biskra, Algeria","{""industry"":""None at present"",""name"":""None at ...",I have fifteen years of experience in the oil ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
8,random-id-4820,Random Name,NG,Volkswagen Product at Random Auto Sales,Nigeria,"{""industry"":""CollinsCAR-Automobile_inv.org"",""n...",We encourage you to browse our online inventor...,"[{""attribution"":""By Random Name"",""created_at"":...","[{""company"":""Random Auto Sales"",""description_h...",https://www.linkedin.com/in/random-id-4820,"[{""profile_link"":""https://ng.linkedin.com/in/t...",Advance Auto Engineering,"[{""degree"":""master degree of junior"",""descript...",,https://media.licdn.com/dms/image/C5103AQFdf27...,,,,,,13,13,,Random Auto Sales,,,,,https://www.linkedin.com/in/random-id-4820,random-id-4820
9,random-id-9025,Random Name,UK,,,"{""company_id"":""oldmill"",""industry"":""Old Mill"",...",I have worked in Financial Services since late...,[],[],https://www.linkedin.com/in/random-id-9025?_l=en,[],University of Exeter,[],,https://media.licdn.com/dms/image/D4D03AQGJiEd...,[],[],[],[],[],739,500,oldmill,Random Company,[],[],"[{},{}]",,https://www.linkedin.com/in/random-id-9025,random-id-9025
10,random-id-5837,Random Name,EG,Food Safety & hygiene coordinator at Random Ho...,Cairo,"{""company_id"":""steigenberger"",""industry"":""Stei...",,[],"[{""description"":""Ø¬Ù†ÙˆØ¨ Ø³ÙŠÙ†Ø§Ø¡ Ø´Ø±Ù… Ø§...",https://www.linkedin.com/in/random-id-5837?_l=en,[],Cairo University,"[{""degree"":""Bachelor's degree"",""description"":n...",,https://media.licdn.com/dms/image/C4D03AQHdThz...,[],[],[],[],[],2000,500,steigenberger,Random Hotels and Resorts,[],[],[],,https://www.linkedin.com/in/random-id-5837,random-id-5837
11,random-id-5847,Random Name,GB,Community Associate at Random Labs Cambridge,Greater Cambridge Area,"{""industry"":""Random Labs"",""name"":""Random Labs""...",Experienced in hospitality with a demonstrated...,,"[{""company"":""Random Labs"",""description"":""As Co...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
12,random-id-12286a197,Random Name,EG,Senior Media Buyer | Marketing Strategist | Go...,New Cairo,"{""company_id"":""cmg-city-mega-group"",""industry""...",I've spent 3 years optimizing campaigns and cr...,[],"[{""description"":""Cairo, Egypt"",""description_ht...",https://www.linkedin.com/in/random-id-12286a197,[],Beni-Suef University,"[{""degree"":""Bachelor's degree"",""description"":n...",,https://media.licdn.com/dms/image/D4D03AQHvot_...,[],[],[],[],[],117,117,cmg-city-mega-group,CMG | City Mega Group,[],[],[],,https://www.linkedin.com/in/random-id-12286a197,random-id-12286a197

In [220]:
df_final = data.rename(columns=
{0:'id',
 1:'name',
 2:'country_code',
 3:'position',
 4:'city',
 5:'current_company',
 6:'about',
 7:'posts',
 8:'experience',
 9:'url',
 10:'people_also_viewed',
 11:'educations_details',
 12:'education',
 13:'recommendations_count',
 14:'avatar',
 15:'languages',
 16:'certifications',
 17:'recommendations',
 18:'volunteer_experience',
 19:'courses',
 20:'followers',
 21:'connections',
 22:'current_company_company_id',
 23:'current_company_name',
 24:'publications',
 25:'patents',
 26:'projects',
 27:'organizations',
 28:'input_url',
 29:'linkedin_id;;;;'})

In [221]:
df_final

,id,name,country_code,position,city,current_company,about,posts,experience,url,people_also_viewed,educations_details,education,recommendations_count,avatar,languages,certifications,recommendations,volunteer_experience,courses,followers,connections,current_company_company_id,current_company_name,publications,patents,projects,organizations,input_url,linkedin_id;;;;
0,id,name,country_code,position,city,current_company,about,posts,experience,url,people_also_viewed,educations_details,education,recommendations_count,avatar,languages,certifications,recommendations,volunteer_experience,courses,followers,connections,current_company_company_id,current_company_name,publications,patents,projects,organizations,input_url,linkedin_id
1,random-id-2468,Random Name,KW,,Kuwait,"{""company_id"":""-seara"",""industry"":""Seara Alime...",Experienced Unit Sales Manager with a demonstr...,"[{""attribution"":""By Random Name"",""created_at"":...",,https://www.linkedin.com/in/random-id-2468,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Alexandria University,,,https://media.licdn.com/dms/image/D4D03AQEK_J4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,-seara,Random Alimentos LTDA,,,,,https://www.linkedin.com/in/random-id-2468,random-id-2468 ``` &#8203;:citation[oaicite:0]...
2,random-id-1357,Random Name,IN,Random EduTech,"Noida, Uttar Pradesh, India","{""company_id"":""byjus"",""industry"":""BYJU'S"",""lin...",,,"[{""company"":""Random EduTech"",""company_id"":""byj...",https://www.linkedin.com/in/random-id-1357,"[{""profile_link"":""https://in.linkedin.com/in/a...",Delhi University,"[{""degree"":""Bachelor's degree"",""description"":n...",,https://media.licdn.com/dms/image/D4D03AQGrszI...,,,,,,,112,byjus,Random EduTech,,,,"[{""end_date"":""Present"",""membership_number"":nul...",https://www.linkedin.com/in/random-id-1357,random-id-1357
3,random-id-8642,Random Name,,,,"{""company_id"":""shepard-exposition-services"",""i...",EXPERIENCED EVENT PLANNER with over three year...,[],[],https://www.linkedin.com/in/random-id-8642?_l=en,[],Guilford Technical Community College,[],,https://media.licdn.com/dms/image/C4E03AQGGXHL...,[],[],[],[],[],190,188,shepard-exposition-services,Random Event Services,[],[],[],,https://www.linkedin.com/in/random-id-8642?_l=en,random-id-8642
4,random-id-9512,Random Name,UK,Design Engineer (System health) at Random Powe...,Galashiels,"{""company_id"":""edf-energy"",""industry"":""EDF (UK...",,[],"[{""description"":""Torness Nuclear Power Station...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5,random-id-8642,Random Name,KW,,Kuwait,"{""company_id"":""global-infinity"",""industry"":""Gl...",Experienced Chief Executive Officer with a dem...,,,https://www.linkedin.com/in/random-id-8642,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Cairo University,,,https://static.licdn.com/aero-v1/sc/h/9c8pery4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,global-infinity,Random Contracting,,,,,https://www.linkedin.com/in/random-id-8642,random-id-8642
6,random-id-7531,Random Name,KW,,Kuwait,"{""company_id"":""global-infinity"",""industry"":""Gl...",Experienced Chief Executive Officer with a dem...,,,https://www.linkedin.com/in/random-id-7531,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Cairo University,,,https://static.licdn.com/aero-v1/sc/h/9c8pery4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,global-infinity,Random Contracting,,,,,https://www.linkedin.com/in/random-id-7531,random-id-7531
7,random-id-7890,Random Name,DZ,Logging Operations & Petrophysical QA/QC super...,"Biskra, Algeria","{""industry"":""None at present"",""name"":""None at ...",I have fifteen years of experience in the oil ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
8,random-id-4820,Random Name,NG,Volkswagen Product at Random Auto Sales,Nigeria,"{""industry"":""CollinsCAR-Automobile_inv.org"",""n...",We encourage you to browse our online inventor...,"[{""attribution"":""By Random Name"",""created_at"":...","[{""company"":""Random Auto Sales"",""description_h...",https://www.linkedin.com/in/random-id-4820,"[{""profile_link"":""https://ng.linkedin.com/in/t...",Advance Auto Engineering,"[{""degree"":""master degree of junior"",""descript...",,https://media.licdn.com/dms/image/C5103AQFdf27...,,,,,,13,13,,Random Auto Sales,,,,,https://www.linkedin.com/in/random-id-4820,random-id-4820
9,random-id-9025,Random Name,UK,,,"{""company_id"":""oldmill"",""industry"":""Old Mill"",...",I have worked in Financial Services since late...,[],[],https://www.linkedin.com/in/random-id-9025?_l=en,[],University of Exeter,[],,https://media.licdn.com/dms/image/D4D03AQGJiEd...,[],[],[],[],[],739,500,oldmill,Random Company,[],[],"[{},{}]",,https://www.linkedin.com/in/random-id-9025,random-id-9025
10,random-id-5837,Random Name,EG,Food Safety & hygiene coordinator at Random Ho...,Cairo,"{""company_id"":""steigenberger"",""industry"":""Stei...",,[],"[{""description"":""Ø¬Ù†ÙˆØ¨ Ø³ÙŠÙ†Ø§Ø¡ Ø´Ø±Ù… Ø§...",https://www.linkedin.com/in/random-id-5837?_l=en,[],Cairo University,"[{""degree"":""Bachelor's degree"",""description"":n...",,https://media.licdn.com/dms/image/C4D03AQHdThz...,[],[],[],[],[],2000,500,steigenberger,Random Hotels and Resorts,[],[],[],,https://www.linkedin.com/in/random-id-5837,random-id-5837
11,random-id-5847,Random Name,GB,Community Associate at Random Labs Cambridge,Greater Cambridge Area,"{""industry"":""Random Labs"",""name"":""Random Labs""...",Experienced in hospitality with a demonstrated...,,"[{""company"":""Random Labs"",""description"":""As Co...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
12,random-id-12286a197,Random Name,EG,Senior Media Buyer | Marketing Strategist | Go...,New Cairo,"{""company_id"":""cmg-city-mega-group"",""industry""...",I've spent 3 years optimizing campaigns and cr...,[],"[{""description"":""Cairo, Egypt"",""description_ht...",https://www.linkedin.com/in/random-id-12286a197,[],Beni-Suef University,"[{""degree"":""Bachelor's degree"",""description"":n...",,https://media.licdn.com/dms/image/D4D03AQHvot_...,[],[],[],[],[],117,117,cmg-city-mega-group,CMG | City Mega Group,[],[],[],,https://www.linkedin.com/in/random-id-12286a197,random-id-12286a197

In [222]:
df_final = df_final.drop(data.index[0])

In [223]:
df_final.columns

Index(['id', 'name', 'country_code', 'position', 'city', 'current_company',
       'about', 'posts', 'experience', 'url', 'people_also_viewed',
       'educations_details', 'education', 'recommendations_count', 'avatar',
       'languages', 'certifications', 'recommendations',
       'volunteer_experience', 'courses', 'followers', 'connections',
       'current_company_company_id', 'current_company_name', 'publications',
       'patents', 'projects', 'organizations', 'input_url', 'linkedin_id;;;;'],
      dtype='object')

In [224]:
df_final.head(1)

,id,name,country_code,position,city,current_company,about,posts,experience,url,people_also_viewed,educations_details,education,recommendations_count,avatar,languages,certifications,recommendations,volunteer_experience,courses,followers,connections,current_company_company_id,current_company_name,publications,patents,projects,organizations,input_url,linkedin_id;;;;
1,random-id-2468,Random Name,KW,,Kuwait,"{""company_id"":""-seara"",""industry"":""Seara Alime...",Experienced Unit Sales Manager with a demonstr...,"[{""attribution"":""By Random Name"",""created_at"":...",,https://www.linkedin.com/in/random-id-2468,"[{""profile_link"":""https://kw.linkedin.com/in/m...",Alexandria University,,,https://media.licdn.com/dms/image/D4D03AQEK_J4...,"[{""subtitle"":"" Professional working proficienc...",,,,,,500,-seara,Random Alimentos LTDA,,,,,https://www.linkedin.com/in/random-id-2468,random-id-2468 ``` &#8203;:citation[oaicite:0]...